name: Run Python Tests
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  matrix:
    strategy:
      matrix:
        os: [windows-latest,macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    runs-on: ${{matrix.os}}
    env:
      SDL_VIDEODRIVER: "dummy"
      SDL_AUDIODRIVER: "disk"
    steps:
      - uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install universal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install ubuntu dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          echo ${{matrix.os}}=='ubuntu-latest'
          echo ${{matrix.os}}
          echo "is matrix.os"
          sudo apt-get install -y xserver-xorg
      - name: confirm display
        run: echo "temp test confirm display driver is active and available... in the future when tests are actually written"
      - name: Run tests with unittest 
        run: python -m unittest test.py 


